name: Build LiteRT Native Libraries

on:
  workflow_dispatch:
  push:
    branches: [ feat/native ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Compiler versions
        run: |
          gcc --version
          g++ --version
          cmake --version    

      - name: Set up dependencies
        run: sudo apt-get update && sudo apt-get install -y clang

      - name: Build LiteRT (Linux)
        run: |
          cmake -S core/native/LiteRT/litert -B build-release \
                -DCMAKE_BUILD_TYPE=Release \
                -DLITERT_AUTO_BUILD_TFLITE=OFF \
                -DLITERT_ENABLE_GPU=OFF \
                -DLITERT_ENABLE_NPU=OFF \
                -DLITERT_DISABLE_KLEIDIAI=ON
          cmake --build build-release -j1

#      - name: Prepare Artifacts
#        run: |
#          mkdir -p core/generated/linux/lib
#          mkdir -p core/generated/linux/include
#          find build-release -name "*.so" -exec cp {} core/generated/linux/lib/ \;
#          cp -r core/native/LiteRT/litert/c/*.h core/generated/linux/include/
#
#      - uses: actions/upload-artifact@v4
#        with:
#          name: litert-linux-x64
#          path: core/generated/linux/
#
#  build-windows:
#    runs-on: windows-latest
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          submodules: recursive
#      - name: Build LiteRT (Windows)
#        run: |
#          mkdir build_win
#          cd build_win
#          cmake ../core/native/LiteRT/litert -DCMAKE_BUILD_TYPE=Release -DLITERT_BUILD_DYNAMIC_LIB=ON
#          cmake --build . --config Release -j $env:NUMBER_OF_PROCESSORS
#
#      - name: Prepare Artifacts
#        shell: bash
#        run: |
#          mkdir -p core/generated/win/lib
#          mkdir -p core/generated/win/include
#          cp build_win/Release/*.dll core/generated/win/lib/
#          cp -r core/native/LiteRT/litert/c/*.h core/generated/win/include/
#
#      - uses: actions/upload-artifact@v4
#        with:
#          name: litert-win-x64
#          path: core/generated/win/
#
#  build-macos:
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          submodules: recursive
#      - name: Build LiteRT (macOS)
#        run: |
#          mkdir -p build_mac && cd build_mac
#          cmake ../core/native/LiteRT/litert -DCMAKE_BUILD_TYPE=Release -DLITERT_BUILD_DYNAMIC_LIB=ON
#          cmake --build . -j $(sysctl -n hw.ncpu)
#
#      - name: Prepare Artifacts
#        run: |
#          mkdir -p core/generated/mac/lib
#          mkdir -p core/generated/mac/include
#          cp build_mac/*.dylib core/generated/mac/lib/
#          cp -r core/native/LiteRT/litert/c/*.h core/generated/mac/include/
#
#      - uses: actions/upload-artifact@v4
#        with:
#          name: litert-mac
#          path: core/generated/mac/
